### ISSUE TITLE
Fehler beim Beispiel-Code

### ISSUE THREAD

**Issue by rgruosso** [Bangee44/MMM-meteoblueCurrent#1]
Hallo Bangee44,

tolles Modul! Habe ich grad bei meinem Magic Mirror 2 integriert und funktioniert wunderbar. Habe noch eine Fehler beim Beispiel-Code gefunden:

modules: [
    {
        ...
            id: '008503203', // Trainstation ID
            maximumEntries: '10', // Max departures displayed
        }
    },
]

Das Komme nach maximumEntries: '10' ist falsch, oder?

Grüsse
Raffaello

**Comment by Bangee44** [comment]
Hmm.. aber nicht in diesem Modul, ich glaube Du meinst im Zugverbindungsmodul! :-) ich schaus gleich an.
